### ISSUE TITLE
Support visualizing multiple `SpatialData` objects

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/napari-spatialdata#112]
Works on the `spatialdata` branch, needs to be ported in `main`.

**Comment by kevinyamauchi** [comment]
@melonora , would you be able to take this one? @LucaMarconato has some demo code already on the spatialdata branch. @LucaMarconato , can please link the code?

**Comment by LucaMarconato** [comment]
Yes, something like the commented line here works: https://github.com/scverse/napari-spatialdata/blob/2590e1e8191091820478b470ef7aee8bfd322be8/src/napari_spatialdata/interactive.py#LL687C1-L687C42

**Comment by melonora** [comment]
I have this also in follow up PRs which I did not open yet. I keep track of the spatialdata object in the layer metadata, similar to what Luca did on the spatialdata branch.

**Comment by melonora** [comment]
I can open them, but they are branched from the layer_visibility branch so that was why I was waiting a bit.

**Comment by LucaMarconato** [comment]
Thanks Wouter, I prefer 1. since it was what we used so far, but we could also allow the user to use `add_sdata()` later (this is actually what happens in the `spatialdata` branch: there is an equivalent private function that allows for that).

Drag and drops interactions would be also nice, but we can add it later.

Re the multiple names I would prefer having napari automatically handle it so that we don't have to add extra suffix logic.

**Comment by melonora** [comment]
I would say both option 1 and 2 are very doable, as initially the only thing that happens when adding a `SpatialData` object should be populating the `CoordinateSystemWidget` and the `ElementWidget`. This can be done by just adding items.

Regarding the names I think it would be nice to modify the copy names of the layer in such a way that it at least indicates which layers share the `SpatialData` object, but I would have to find out first what would be the best way to achieve that.

**Comment by melonora** [comment]
closed by #136
