### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by goanpeca** [scverse/napari-spatialdata#183]
Hello team, while working on https://github.com/conda-forge/napari-spatialdata-feedstock/pull/1

We noticed some updates needed for the dependencies

# Imported but not in requirements

- cycler
- dask-core
- geopandas
- matplotlib-base
- napari-matplotlib
- packaging 
- pandas
- scikit-learn
- scipy
- superqt
- vispy

# Required but not imported
- magicgui  
- scikit-image 
- squidpy 

Could these be updated for the next release?

Cheers 🚀

**Comment by melonora** [comment]
Hey! yes will take a look.

**Comment by LucaMarconato** [comment]
Thanks for reporting this! I have locked into this (`ripgrep` and some filtering via emacs) and I have obtained these lists of packages that are imported respectively in `napari_spatialdata`, in the tests and in the docs. I will update the requirements to match these lists.

### `napari_spatialdata` package
```
PIL
anndata
click
cycler
dask
datatree
geopandas
loguru
matplotlib
multiscale_spatial_image
napari
napari_matplotlib
napari_plugin_engine
numba
numpy
packaging
pandas
pytestqt
qtpy
scipy
shapely
sklearn
spatial_image
spatialdata
superqt
vispy
xarray
```

###  tests (some packages are already imported above, remove)
```
anndata
click
dask
logging
loguru
matplotlib
multiscale_spatial_image
napari
numpy
pandas
pytest
qtpy
scipy
skimage
spatialdata
```

### docs (some tests are already used in the main package or test, remove)
```
matplotlib
napari
scanpy
spatialdata
sphinx
squidpy
```

**Comment by LucaMarconato** [comment]
The lists above still miss some packages, for instance the ones that are used internally by `sphinx` when building the docs. And also some packages needs to be renamed since I am listing the import name and not the pip name.

There are some differences with respect to your list, for instance `squidpy` is only used in the docs, so it should not appear in the conda configuration. Also I am using `dask` and not `dask-core`, is this ok?

I will test the new requirements (linked PR) and eventually adjust the requirements there.

**Comment by LucaMarconato** [comment]
I made a release with the update dependencies.

**Comment by goanpeca** [comment]
`Also I am using dask and not dask-core, is this ok?` 

Hi sorry I did not reply. dask-core is conda forge package that is more or less equialent to `dask` on pypi, so yeah all good.

Thanks for updating the deps :)
